In [1]:
import pandas as pd
import numpy as np

In [2]:
data =  pd.read_csv( 'https://query.data.world/s/wh6j7rxy2hvrn4ml75ci62apk5hgae' ) 
data.head()

C:\Users\elegb\New folder\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


country  year  country_code        record      crop_land   grazing_land  \
0  Armenia  1992             1    AreaPerCap       0.140292       0.199546   
1  Armenia  1992             1     AreaTotHA  483000.000000  687000.000000   
2  Armenia  1992             1  BiocapPerCap       0.159804       0.135261   
3  Armenia  1992             1  BiocapTotGHA  550176.242700  465677.972200   
4  Armenia  1992             1  EFConsPerCap       0.387510       0.189462   

   forest_land  fishing_ground  built_up_land    carbon         total QScore  
0  0.097188051        0.036888       0.029320  0.000000  5.032351e-01     3A  
1       334600   127000.000000  100943.000800  0.000000  1.732543e+06     3A  
2  0.084003213        0.013742       0.033398  0.000000  4.262086e-01     3A  
3  289207.1078    47311.551720  114982.279300  0.000000  1.467355e+06     3A  
4     1.26E-06        0.004165       0.033398  1.114093  1.728629e+00     3A

In [3]:
#check distribution of the target variable
data.QScore.value_counts()

3A    51481
2A    10576
2B    10096
1A       16
1B       16
Name: QScore, dtype: int64

In [4]:
data.isna().sum()

country               0
year                  0
country_code          0
record                0
crop_land         20472
grazing_land      20472
forest_land       20472
fishing_ground    20473
built_up_land     20473
carbon            20473
total                 9
QScore                1
dtype: int64

In [5]:
#drop rows with missing data
data = data.dropna()
data.isna().sum()

country           0
year              0
country_code      0
record            0
crop_land         0
grazing_land      0
forest_land       0
fishing_ground    0
built_up_land     0
carbon            0
total             0
QScore            0
dtype: int64

In [6]:
data.QScore.value_counts()

3A    51473
2A      224
1A       16
Name: QScore, dtype: int64

In [7]:
#combine class 2A and 1A
data[ 'QScore' ] = data[ 'QScore' ].replace([ '1A' ], '2A' ) 
data.QScore.value_counts()

3A    51473
2A      240
Name: QScore, dtype: int64

In [8]:
df_2A = data[data.QScore== '2A' ]
df_3A = data[data.QScore== '3A' ].sample( 350 )
data_df = df_2A.append(df_3A) 
data_df

country  year  country_code        record     crop_land  \
1536         Algeria  2016             4    AreaPerCap  2.072989e-01   
1537         Algeria  2016             4     AreaTotHA  8.417600e+06   
1538         Algeria  2016             4  BiocapPerCap  2.021916e-01   
1539         Algeria  2016             4  BiocapTotGHA  8.210214e+06   
1540         Algeria  2016             4  EFConsPerCap  6.280528e-01   
...              ...   ...           ...           ...           ...   
4779      Bangladesh  1975            16  BiocapTotGHA  1.905331e+07   
50286  Guinea-Bissau  1980           175  EFConsPerCap  3.190643e-01   
38041         Malawi  1970           130     AreaTotHA  1.867000e+06   
53934    Saint Lucia  2000           189  EFConsPerCap  6.038479e-01   
2426       Argentina  1978             9  BiocapPerCap  1.502377e+00   

       grazing_land  forest_land  fishing_ground  built_up_land    carbon  \
1536   8.112722e-01  0.048357265    2.258528e-02   2.998367e-02  0.000000   
1537   3.294260e+07      1963600    9.171000e+05   1.217520e+06  0.000000   
1538   2.636077e-01  0.027166736    7.947991e-03   2.924496e-02  0.000000   
1539   1.070408e+07  1103135.245    3.227369e+05   1.187524e+06  0.000000   
1540   1.810332e-01  0.162800822    1.472910e-02   2.924496e-02  1.391455   
...             ...          ...             ...            ...       ...   
4779   5.343341e+05  789232.1747    8.592339e+06   2.222292e+06  0.000000   
50286  3.693150e-01   0.85258303    7.422693e-03   3.357685e-02  0.102539   
38041  1.840000e+06   3912738.99    2.420000e+06   1.311170e+05  0.000000   
53934  3.067653e-01  0.313655814    2.997091e-01   2.663868e-03  1.531196   
2426   2.695161e+00  1.242554809    2.619475e+00   5.817709e-02  0.000000   

              total QScore  
1536   1.119497e+00     2A  
1537   4.545842e+07     2A  
1538   5.301590e-01     2A  
1539   2.152769e+07     2A  
1540   2.407316e+00     2A  
...             ...    ...  
4779   3.119151e+07     3A  
50286  1.684501e+00     3A  
38041  1.017086e+07     3A  
53934  3.057838e+00     3A  
2426   8.117745e+00     3A  

[590 rows x 12 columns]

In [9]:
import sklearn.utils
data_df = sklearn.utils.shuffle(data_df)
data_df = data_df.reset_index(drop = True)
data_df.shape

(590, 12)

In [10]:
data_df = data_df.drop(columns=[ 'country_code' , 'country' , 'year' ]) 
X = data_df.drop(columns= 'QScore' )
y = data_df[ 'QScore' ] 


In [11]:
#split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size= 0.3 , random_state= 0 )
y_train.value_counts() 

3A    245
2A    168
Name: QScore, dtype: int64

In [12]:
y_test.shape, x_test.shape

((177,), (177, 8))

In [13]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
x_train.record = encoder.fit_transform(x_train.record)
x_test.record = encoder.transform(x_test.record) 

In [14]:
import imblearn
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state= 1 )
x_train_balanced, y_balanced = smote.fit_resample(x_train, y_train) 

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_train_df = scaler.fit_transform(x_train_balanced.drop(columns=[ 'record' ]))
normalised_train_df = pd.DataFrame(normalised_train_df,
columns=x_train_balanced.drop(columns=[ 'record' ]).columns)
normalised_train_df[ 'record' ] = x_train_balanced[ 'record' ] 

In [16]:
x_test = x_test.reset_index(drop= True )
normalised_test_df = scaler.transform(x_test.drop(columns=[ 'record' ]))
normalised_test_df = pd.DataFrame(normalised_test_df,
columns=x_test.drop(columns=[ 'record' ]).columns)
normalised_test_df[ 'record' ] = x_test[ 'record' ] 


In [17]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(normalised_train_df, y_balanced) 

LogisticRegression()

In [18]:
#Cross-validation and accuracy
from sklearn.model_selection import cross_val_score
scores = cross_val_score(log_reg, normalised_train_df, y_balanced, cv= 5 , scoring= 'f1_macro' )
print(y_test.shape)
scores

(177,)


array([0.51243781, 0.50691824, 0.5006646 , 0.50885399, 0.49707602])

In [19]:
#K-Fold Cross Validation
from sklearn.model_selection import KFold
kf = KFold(n_splits= 5 )
kf.split(normalised_train_df)
f1_scores = []
#run for every split
for train_index, test_index in kf.split(normalised_train_df):
    x_train, x_test = normalised_train_df.iloc[train_index], normalised_train_df.iloc[test_index]
    y_train, yy_test = y_balanced[train_index], y_balanced[test_index]
    model = LogisticRegression().fit(x_train, y_train)
 #save result to list
    f1_scores.append(sklearn.metrics.f1_score(y_true=yy_test, y_pred=model.predict(x_test),pos_label= '2A' )* 100 )
print(y_test.shape)
f1_scores

(177,)


[64.0625, 56.00000000000001, 56.60377358490567, 50.40650406504065, 0.0]

In [20]:
#Stratified K-Fold Cross Validation
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits= 5 , shuffle= True , random_state= 1 )
f1_scores = []
#run for every split
for train_index, test_index in skf.split(normalised_train_df, y_balanced):
    x_train, x_test = np.array(normalised_train_df)[train_index],np.array(normalised_train_df)[test_index]
    y_train, yy_test = y_balanced[train_index], y_balanced[test_index]
    model = LogisticRegression().fit(x_train, y_train)
 #save result to list
    f1_scores.append(sklearn.metrics.f1_score(y_true=yy_test, y_pred=model.predict(x_test), pos_label= '2A' ))
print(y_test.shape)
f1_scores

(177,)


[0.6870229007633588,
 0.44036697247706424,
 0.485981308411215,
 0.5818181818181818,
 0.588235294117647]

In [21]:
#Leave One Out Cross Validation (LOOCV) 
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
scores = cross_val_score(LogisticRegression(), normalised_train_df, y_balanced, cv=loo, scoring= 'f1_macro' )
average_score = scores.mean() * 100 
print(y_test.shape)
average_score

(177,)


50.61224489795918

In [22]:
#Confusion Matrix
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score,confusion_matrix
new_predictions = log_reg.predict(normalised_test_df)
cnf_mat = confusion_matrix(y_true=y_test , y_pred=new_predictions, labels=[ '2A' , '3A' ])
cnf_mat

array([[52, 20],
       [78, 27]], dtype=int64)

In [24]:
#Accuracy
accuracy = accuracy_score(y_true=y_test, y_pred=new_predictions)
print( 'Accuracy: {}' .format(round(accuracy* 100 ), 2 ))

Accuracy: 45


In [26]:
#Precision
precision = precision_score(y_true=y_test, y_pred=new_predictions, pos_label= '2A' )
print( 'Precision: {}' .format(round(precision* 100 ), 2 )) #prints 41.0
#Recall
recall = recall_score(y_true=y_test, y_pred=new_predictions, pos_label= '2A' )
print( 'Recall: {}' .format(round(recall* 100 ), 2 )) #prints 51.0
#F1-Score
f1 = f1_score(y_true=y_test, y_pred=new_predictions, pos_label= '2A' )
print( 'F1: {}' .format(round(f1* 100 ), 2 )) #prints 45.0 

Precision: 40
Recall: 72
F1: 51


In [30]:
from sklearn.tree import DecisionTreeClassifier
dec_tree = DecisionTreeClassifier()
model =dec_tree.fit(normalised_train_df, y_balanced)
y_pred = model.predict(normalised_test_df)


In [31]:
cnf_mat = confusion_matrix(y_true=y_test , y_pred=y_pred, labels=[ '2A' , '3A' ])
cnf_mat

array([[48, 24],
       [56, 49]], dtype=int64)

In [34]:
data.shape

(10000, 14)

In [33]:
data.stabf.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

1    6380
0    3620
Name: stabf, dtype: int64

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab  stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347      1  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957      0  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471      1  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871      1  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860      1

In [38]:
df_0 = data[data.stabf == 0 ]
df_1 = data[data.stabf == 1 ].sample( 3700 )
sample_data  = df_0.append(df_1) 
sample_data.shape

(7320, 14)

In [39]:
sample_data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
1   9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
5   6.999209  9.109247  3.784066  4.267788  4.429669 -1.857139 -0.670397   
8   4.689852  4.007747  1.478573  3.733787  4.041300 -1.410344 -1.238204   
10  5.930110  6.730873  6.245138  0.533288  2.327092 -0.702501 -1.116920   
12  1.616787  2.939228  0.819791  4.191804  3.752282 -1.484885 -1.280581   

          p4        g1        g2        g3        g4      stab  stabf  
1  -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957      0  
5  -1.902133  0.261793  0.077930  0.542884  0.469931 -0.017385      0  
8  -1.392751  0.269708  0.250364  0.164941  0.482439 -0.038677      0  
10 -0.507671  0.239816  0.563110  0.164461  0.753701 -0.028411      0  
12 -0.986816  0.899698  0.866546  0.303921  0.077610 -0.048617      0

In [40]:
sample_data = sample_data.reset_index(drop = True)
sample_data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
1  6.999209  9.109247  3.784066  4.267788  4.429669 -1.857139 -0.670397   
2  4.689852  4.007747  1.478573  3.733787  4.041300 -1.410344 -1.238204   
3  5.930110  6.730873  6.245138  0.533288  2.327092 -0.702501 -1.116920   
4  1.616787  2.939228  0.819791  4.191804  3.752282 -1.484885 -1.280581   

         p4        g1        g2        g3        g4      stab  stabf  
0 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957      0  
1 -1.902133  0.261793  0.077930  0.542884  0.469931 -0.017385      0  
2 -1.392751  0.269708  0.250364  0.164941  0.482439 -0.038677      0  
3 -0.507671  0.239816  0.563110  0.164461  0.753701 -0.028411      0  
4 -0.986816  0.899698  0.866546  0.303921  0.077610 -0.048617      0

In [43]:
x = sample_data.drop(columns = 'stabf')
y = sample_data.stabf

In [44]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size= 0.3 , random_state= 42 )
y_train.value_counts()

ValueError: Found input variables with inconsistent numbers of samples: [590, 7320]

In [ ]:
another
import json
with open(r'C:\Users\elegb\Desktop\habeeb\tweet-json.txt', encoding = 'utf8') as file:
    list = []
    for line in file:
        list.append(json.loads(line))

In [ ]:
data = pd.DataFrame(list)
data.columns

In [ ]:
data 

In [ ]:
data = data[['id','favorite_count','retweet_count','source', 'lang']]

In [ ]:
data.rename(columns = {'id': 'tweet_id'}, inplace = True)
data